plugins:
  mingle_enabled:
    default: false
    client: true
  mingle_delivery_user_id:
    default: -2
  mingle_group_name:
    default: "trust_level_1"
  mingle_group_size:
    default: 2
    min: 2
  mingle_interval_number:
    default: 1
  mingle_interval_type:
    enum: "Mingle::IntervalOptions"
    default: weeks
  mingle_post_id:
    default: -1
    hidden: true
  mingle_theme_id:
    default: -1
    hidden: true
