plugins:
  mingle_enabled:
    default: false
  mingle_delivery_user_id:
    default: -2
  mingle_group_name:
    default: "trust_level_1"
  mingle_interval_number:
    default: 1
  mingle_interval_type:
    enum: "Mingle::IntervalOptions"
    default: weeks
  mingle_default_message_title:
    default: "You've been matched for a Mingle!"
    hidden: true
  mingle_default_message_body:
    default: |
      _Thanks for installing the Mingle plugin! :smiling_face_with_three_hearts: This is a template for the messages which will go out to paired users._

      _Some things to note!_
      - _You can customize the title of the message that goes out by editing the title of this post_
      - _Anything **below** the horizontal line will appear in the message which goes out to matches._
      - _Note that you can use the following format to apply user-specific messaging to the template_

      > Hey, %{1.name}, meet %{2.name}!
      > Did you know that %{1.custom_fields.fun_fact}, while %{2.custom_fields.fun_fact}?

      <sup>^^ PS, this works for the message title, too! :exploding_head:</sup>

      _Customize to your heart's content, and be sure to report any issues [here](https://www.github.com/gdpelican/mingle/issues)!_ :star2: :star2: :star2:

      ------------------

      Hey, %{1.name}, meet %{2.name}; they're awesome! Why not schedule some time to get to know each other a little bit?
    hidden: true
  mingle_post_id:
    default: -1
    hidden: true
